# Generated by Django 4.0.4 on 2022-04-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, upload_to='courses/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resource', models.FileField(upload_to='resource/')),
                ('length', models.IntegerField()),
            ],
        ),
    ]
